runtime: python

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.12"

env: flex

env_variables:
  FIREBASE_PATH: "gen-lang-client-0263701804-firebase-adminsdk-rjr2c-e90c9bfb5a.json"
  GOOGLE_API_KEY:

entrypoint: uvicorn main:app --host 0.0.0.0 --port 8080